CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE product(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    name text NOT NULL,
    value NUMERIC NOT NULL,
)